# Generated by Django 4.2.1 on 2023-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_patient_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xray_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X_ray_types', models.CharField(max_length=100)),
            ],
        ),
    ]
