# Generated by Django 4.2.1 on 2023-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_xray_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_type', models.CharField(max_length=100)),
            ],
        ),
    ]
