# Generated by Django 4.2.1 on 2023-06-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_lab_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=100)),
            ],
        ),
    ]
