# Generated by Django 4.2.1 on 2023-06-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_booking_labs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('xray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.xray_category')),
            ],
        ),
    ]
