# Generated by Django 4.2.1 on 2023-06-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0012_alter_book_blood_age_alter_book_blood_phoneno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=70)),
                ('phoneno', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.category')),
            ],
        ),
        migrations.AlterField(
            model_name='book_blood',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_blood',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_labs',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_labs',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_xray',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_xray',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='add_doctor',
        ),
    ]
