# Generated by Django 4.2.1 on 2023-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0013_add_doctor_details_alter_book_blood_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('addres', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.CharField(max_length=600)),
            ],
        ),
    ]
