# Generated by Django 4.2.1 on 2023-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings_model',
            name='status',
            field=models.CharField(default='No Booking', max_length=20),
        ),
    ]
